# create the environment from this file with `conda env create -f root_environment.yml`
name: placement
channels:
  - conda-forge
dependencies:
  - pandas
  - numpy
  - matplotlib
  - ipykernel
  - windrose
  - time
  - pytest  
