name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip build-essential

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          activate-environment: gp
          environment-file: root_environment.yml

      - name: Clone and set up FastGaussianPuff
        run: |
          git clone https://github.com/rykerfish/FastGaussianPuff.git
          cd FastGaussianPuff
          conda env update -f environment.yml
          pip install --upgrade pip setuptools wheel
          pip install .
          cd ..

      - name: Install additional dependencies
        run: |
          pip install numpy pandas matplotlib ipykernel windrose pytest

      - name: Run tests
        run: pytest tests
