name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install codespell
        run: |
          sudo apt-get install -y codespell

      - name: Run spell checker
        run: |
          # Ignore common programming words like "function", "init", eSy, y2j93Eo5daK1R1Ph91b, etc.
          codespell --ignore-words-list "function,init,def,ndarray,PyPI,env" .
